title: Kelley Erickson
author: Kelley D. Erickson
email: kerickson22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Showcasing my latest data science projects
show_excerpts: true # set to false to remove excerpts on the homepage



twitter_username: kelephant22
github_username:  kerickson22

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: pages-themes/time-machine@v0.2.0
